name: Biqz-Menu
version: '${project.version}'
main: me.francesco.menu.Menu
api-version: '1.21'
commands:
  menu:
    description: "Apre un menu"
    usage: "/<comando>"
  creamenu:
    description: "Crea un menu"
    usage: "/<comando>"
    permission: "menu.crea"

permissions:
  menu:
    menu.open: true
    menu.reload: true
    menu.create: true
    admin:
      open: true
