name: Biqz-Menu
version: '1.0'
main: me.francesco.menu.Menu
api-version: '1.21'
commands:
  menu:
    description: "Open the menu"
    usage: "/<comando>"

permissions:
  menu:
    menu.open: true
    menu.reload: true
    menu.create: true
    admin:
      open: true
